[env]
ESP_LOGLEVEL = "debug"
DEFMT_LOG = "debug"

[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H743ZITx --log-file=log.txt"

rustflags = [
    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C",
    "force-frame-pointers",
]
